import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import AdminMenu from "@/components/adminMenu";
import { Providers } from "./providers";

const inter = Poppins({ subsets: ["latin"], weight:['100', '300', '700'], variable:'--poppins-font' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={inter.className}>
        <Providers>
          <Header />
          <div className="flex">
            <div className="fixed w-64 p-4 bg-slate-50 h-full ">
              <AdminMenu />
            </div>
            <div className="ml-64  w-full  h-full bg-white p-4">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
