import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import AdminMenu from "@/components/adminMenu";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={inter.className}>
        <Providers>
          <Header />
          <div className="flex p-6 mt-1">
            <div className="fixed w-60">
              <AdminMenu />
            </div>
            <div className="ml-60  w-full">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
