import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/template/header";
import AdminMenu from "@/components/template/adminMenu";
import { Providers } from "./providers";

const inter = Poppins({ subsets: ["latin"], weight: ['100', '300', '700'], variable: '--poppins-font' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body className={inter.className}>
        <Providers>
          <Header />
          <div className="flex">
            <div className="fixed w-72 p-4 bg-white shadow-md h-full">
              <AdminMenu />
            </div>
            <div className="ml-72 w-full h-full bg-white p-4 overflow-hidden">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
